name: Deploy Shiny App

on:
  push:
    branches:
      - main  # Replace with your default branch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Install dependencies
        run: |
          install.packages(c('shiny', 'rsconnect', 'DT'))
          if (!requireNamespace('BiocManager', quietly = TRUE))
            install.packages('BiocManager')
          BiocManager::install('topGO')

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPSIO_TOKEN: ${{ secrets.SHINYAPPSIO_TOKEN }}
          SHINYAPPSIO_SECRET: ${{ secrets.SHINYAPPSIO_SECRET }}
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(name='growthcurvedb',
                                    token=Sys.getenv('SHINYAPPSIO_TOKEN'),
                                    secret=Sys.getenv('SHINYAPPSIO_SECRET'))
          rsconnect::deployApp(appDir = '.', appName = 'Bsub-strains-GOEA')
